#ifndef CSP4CMSIS_VERSION_H
#define CSP4CMSIS_VERSION_H

// CSP4CMSIS version (3.0.0 on). Test it with the preprocessor, e.g.
//   #if CSP4CMSIS_VERSION >= 30000
#define CSP4CMSIS_VERSION_MAJOR 3
#define CSP4CMSIS_VERSION_MINOR 0
#define CSP4CMSIS_VERSION_PATCH 0
#define CSP4CMSIS_VERSION (CSP4CMSIS_VERSION_MAJOR * 10000 + CSP4CMSIS_VERSION_MINOR * 100 + CSP4CMSIS_VERSION_PATCH)

#endif // CSP4CMSIS_VERSION_H
